// <auto-generated />
namespace AspNetMVC_API_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NameRegisterDateUpdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NameRegisterDateUpdated));
        
        string IMigrationMetadata.Id
        {
            get { return "202202070759087_Name RegisterDate Updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
